### ISSUE TITLE
Only one model spawned for multi model unit

### ISSUE THREAD

**Issue by Streyder** [pwestling/battlescribe-roster-parser#15]
Hey there!

If I add a unit of SM Servitors to my list, which consists of 4 servitors, only one is spawned after I selected the model.

**Expected behavior**
Spawn 4 Models as in my list.

[Test Roaster.zip](https://github.com/pwestling/battlescribe-roster-parser/files/3902505/Test.Roaster.zip)

Cheers,
Streyder

**Comment by pwestling** [comment]
Looked into this (finally) - this is due to an issue with the way the battlescribe data is structured that leaves the models in the unit ambiguous. If you are invested in getting this fixed, the best way would be to get in touch with the maintainer of the data file and ask them to either change the Servitor entry in the Servitor selection group to be a "Model" instead of an "Upgrade", or they can move the Servitor Unit Profile from the Root of the Selection Entry to being nested under the Servitor "Upgrade". I know that likely doesn't make a ton of sense, but if you copy and paste this to the data file maintainer they will likely know what it means. 

If the above _does_ makes sense to you, you can use the Battlescribe Data Editor to make the changes yourself on your own data if you wanted to.

Please note the data file maintainers are volunteers like me and it's 100% up to them if they want to make changes to accommodate this kind of tooling.
