### ISSUE TITLE
Necron list with empty label, when inserting code into TTS

### ISSUE THREAD

**Issue by ghost** [pwestling/battlescribe-roster-parser#18]
**Describe the bug**
After code submission in tts, the list given from the bag has an error.
It's giving me a false immortal unit, with an unfinished datasheet.
Currently, my 500 point list has 2 Necron Warriors and 1 Immortal for troops.
TTS thinks I have 1 Necron warrior, and 1 immortal + 1 bugged Immortal tab.

Also, when pressing Numpad 1, there is missing data, and abilities.

**Expected behavior**
A list to be produced when inserting code in TTS that has no error.
In this situation, it should be 1 warrior (x2) and 1 immortal (x1) 

**Upload the Roster**
[ezyzip.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4265451/ezyzip.zip)

**Comment by pwestling** [comment]
I spent a while looking into this tonight, and it turns out to be due to a sort of unfortunate mismatch in how various lists structure their data. The Necron lists place a single "Gauss Blaster" entry in the Immortal unit, which looks to my program like a single special weapon was included in the unit (imagine adding 1 plasma or missile launcher - in this case you want a single model carrying it). There are two work arounds:

1. (Recommended) Use your data and the tool as is. 1 of the produced Immortals will have the Gauss Blaster weapon in its profile. Delete the others, and copy the single correct Immortal 7 times to complete the unit
2. Use the slightly modified data sheet for Necrons I've attached below in BattleScribe by renameing the file to "Necrons.catz" and replacing the file with that name in your BattleScribe data files. When you load your list you'll get an error - click through it, and you'll be able to re-select the weapons for your Immortals, and now the data will be in the correct shape for Battlescribe2TTS to not get confused. You could potentially see if the author of the Necron files is willing to make this change official if this is something you care about.

[Necrons.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4271478/Necrons.zip)

There are possibly some ways I could give the user options to correct issues like this in the UI, but they're going to be pretty large investments so I won't be making those changes right now.
