### ISSUE TITLE
Tau XV8 Crisis Iridium Battle Suit spawnig as Cyclic Ion Blaster

### ISSUE THREAD

**Issue by simuno** [pwestling/battlescribe-roster-parser#24]
Iridium Battle Suit option from Battlescribe spawns as Cyclic Ion Blaster in both models and create army map.

[FSE crisis fire warriors bez dronow 1K.zip](https://github.com/pwestling/battlescribe-roster-parser/files/4433505/FSE.crisis.fire.warriors.bez.dronow.1K.zip)

**Comment by pwestling** [comment]
I've looked at the roster you submitted in TTS and in battlescribe and it all looks correct to me. What may be somewhat confusing is that the Cyclic Ion Blaster has 2 profiles (because it's a plasma weapon), and thus is listed twice on the model that has it. That model is _not_ equipped with the Iridium upgrade in your roster in Battlescribe.
