### ISSUE TITLE
details window UI

### ISSUE THREAD

**Issue by FilippoVivirito** [pwestling/battlescribe-roster-parser#4]
1st of all: magnificent work, this thing is amazing.

the detail window (opened by pressing keypad 1) is much bigger than it needs to be
it has a ton of white space and a very big font, plus it can't scroll with the mousewheel which makes it umcomfortable to use.
I would recommend reducing the font size and shrinking down the layout as much as possible. 

Adding mousewheel scrolling or resizable window would be a nice-to-have touch, also: every time a new popup is spawned all the others reset to the center of the screen

I'd imagine keeping 2 or 3 of those windows open on the side while playing.

again: really great stuff!

**Comment by pwestling** [comment]
You must play at a very different resolution than I do (the text is just large enough to comfortably read on my laptop!). I'll see if there's a good way to make the size controllable. I'll see about mousewheel scrolling but that may be out of my hands.

**Comment by pwestling** [comment]
Ok, a few updates here:
1. It turns out scrolling works, but only if you hover the mouse over the scroll bar specifically. This is a TTS thing and I have no way to make it any better unfortunately.
2. I've fixed the issue where the UI windows reposition themselves on load, and simultaneously fixed an issue where one player repositioning the window for a unit would reposition it for other players as well
3. It's not the most usable solution, but I've added "Advanced Options" to the upload page where you can set the UI size. Making the UI resizable in-game proved exceedingly difficult, so this will hopefully help you out in the short term. I also made the default size a bit smaller than it was before.

I'm going to close this issue because I don't really see myself making a ton more progress on the things you've mentioned here without more info. If you have any other ideas for improvements please open a new issue. I really appreciate the feedback!

**Comment by pwestling** [comment]
So it turns out that the performance cost for the changes that make the windows consistently stay in place is way too much for a bunch of clients. Going to have to revert this behavior to resetting window positions whenever a new one is opened. Going to re-open this ticket as a reminder to myself to think of some new, better way to handle it.

**Comment by FilippoVivirito** [comment]
no biggie

would it be possible to spawn the datasheets generated as cards on the table?
I think I would prefer it to the UI popups actually (especially if they are cards that can be drawn into the player's hand, and zoomed in by holding ALT)
